--- #YAML:1.0
name:               Algorithm-GooglePolylineEncoding
version:            0.01
abstract:           Google's Encoded Polyline Algorithm Format
author:
    - Slaven Rezic <srezic@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  git://github.com/eserte/algorithm-googlepolylineencoding.git
no_index:
    directory:
        - t
        - inc
        - xt
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
